# Generated by Django 2.0.5 on 2018-07-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_book_num_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.CharField(default='http://placehold.it/254x150/ff3546/f5f5f5/&text=No+Image+Found', max_length=250),
            preserve_default=False,
        ),
    ]
